name: food
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  flutter_svg_provider: ^0.1.3
  image: ^2.1.12
  provider: ^4.1.3




dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/ice3.jpg


  fonts:
    - family: Qwigley
      fonts:
        - asset: assets/fonts/qwigley/Qwigley-Regular.ttf
    - family: Dosis
      fonts:
        - asset: assets/fonts/dosis/Dosis-Regular.otf
          weight: 400
        - asset: assets/fonts/dosis/Dosis-Medium.otf
          weight: 500
        - asset: assets/fonts/dosis/Dosis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/dosis/Dosis-Bold.otf
          weight: 800
        - asset: assets/fonts/dosis/Dosis-ExtraBold.otf
          weight: 900
